### ISSUE TITLE
Abort  on windows 32bit build

### ISSUE THREAD

**Issue by devmiyax** [wjakob/nanogui#180] opened 2016-12-07 04:47 UTC
When I use nanogui 32bit build on windows 7 64bit.
It crashes on startup. Can you help?

below is the call stack when this abort is happend.

```
>	myexe.exe!issue_debug_notification(const wchar_t * const message) line 125	C++
 	myexe.exe!__acrt_report_runtime_error(const wchar_t * message) line 142	C++
 	myexe.exe!abort() line 51	C++
 	myexe.exe!common_assert_to_stderr_direct(const wchar_t * const expression, const wchar_t * const file_name, const unsigned int line_number) line 124	C++
 	myexe.exe!common_assert_to_stderr<wchar_t>(const wchar_t * const expression, const wchar_t * const file_name, const unsigned int line_number) line 138	C++
 	myexe.exe!common_assert<wchar_t>(const wchar_t * const expression, const wchar_t * const file_name, const unsigned int line_number, void * const return_address) line 383	C++
 	myexe.exe!_wassert(const wchar_t * expression, const wchar_t * file_name, unsigned int line_number) line 404	C++
 	myexe.exe!Eigen::internal::plain_array<float,4,0,16>::plain_array<float,4,0,16>() line 86	C++
 	myexe.exe!Eigen::DenseStorage<float,4,4,1,0>::DenseStorage<float,4,4,1,0>(int __formal, int __formal, int __formal) line 134	C++
 	myexe.exe!Eigen::PlainObjectBase<Eigen::Matrix<float,4,1,0,4,1> >::PlainObjectBase<Eigen::Matrix<float,4,1,0,4,1> >(int a_size, int nbRows, int nbCols) line 475	C++
 	myexe.exe!Eigen::Matrix<float,4,1,0,4,1>::Matrix<float,4,1,0,4,1>(const Eigen::Matrix<float,4,1,0,4,1> & other) line 302	C++
 	myexe.exe!nanogui::Color::Color(const Eigen::Matrix<float,4,1,0,4,1> & color) line 192	C++
 	myexe.exe!nanogui::Color::Color(float r, float g, float b, float a) line 291	C++
 	myexe.exe!nanogui::Screen::Screen() line 95	C++
```

**Comment by omochi** [comment] 2016-12-07 15:40
@devmiyax 
It seems to be crashed by Eigen fixed storage assertion.
I fixed this problem.
Please try with this my branch.
https://github.com/omochi/nanogui/tree/fix-windows-issue

**Comment by wjakob** [comment] 2016-12-12 21:51
The patches related to this issue were merged, so I'll assume the problem is resolved. If not, please comment.

**Closed by wjakob** 2016-12-12 21:51 UTC
