### ISSUE TITLE
Multiple CPP files #define STB_IMAGE_IMPLEMENTATION

### ISSUE THREAD

**Issue by Gibgezr** [wjakob/nanogui#274] opened 2017-10-18 18:37 UTC
I couldn't get NanoGUI to build the examples in VS2017, and it was because nanovg.c already had the line:
#define STB_IMAGE_IMPLEMENTATION
...in it, but each example also tried to define it as well. The stb_image.h documentation clearly states that only ONE source file should define the implementation. If you comment out that line in the examples they link just fine.

**Comment by nzod** [comment] 2019-02-18 12:56
Thanks! Getting rid of the defines indeed works.

**Comment by svenevs** [comment] 2019-05-19 05:26
Closing as duplicate of #179 which should have an official solution soon.  This has had low priority as it only affects building the demo application and static libraries with windows.

**Closed by svenevs** 2019-05-19 05:26 UTC
