### ISSUE TITLE
Bug: Disposing a window with an open popup from a popup button segfaults

### ISSUE THREAD

**Issue by crazycarl** [wjakob/nanogui#326] opened 2018-04-04 05:08 UTC
I also have a working fix.

To produce the bug, create a window with a popup widget. Open the popup and then dispose the window. If you dispose the window while that popup is open, it will segfault while running the function `Popup::refreshRelativePlacement()`. It tries to access the pointer `mParentWindow`, which points to a window that has been disposed.

My fix was to remove the popup from the parent when the button is deconstructed.
```c
PopupButton::~PopupButton() {
    mPopup->parent()->removeChild(mPopup);
}
```
And I did a quick check with Valgrind to make sure it doesn't do anything bad with memory management. The memory management for this library is well designed, so no issues showed up.

**Comment by crazycarl** [comment] 2018-04-04 05:47
Looks like I jumped the gun a little. If the parent window is deleted before the PopupButton, this can cause an error where the reference count to the Window goes below zero.

I'm trying to find a better solution to this problem now.

**Comment by crazycarl** [comment] 2018-04-04 16:34
Okay, so after toying around a bit more and sleeping on the problem, I found that this fixes the issue without creating that reference count issue.

This just makes it so there's no reason to call `Popup::refreshRelativePlacement()` once the button itself is deleted.
```c
PopupButton::~PopupButton() {
    mPopup->setVisible(false);
}
```
Again, Valgrind reports no memory issues with this solution.

**Comment by svenevs** [comment] 2018-04-04 16:58
This seems like a good solution, I'm sure a PR would be welcome :)

TBH I don't quite understand the crash scenario, would you be willing to include a very simple minimum working example?  The only other classes that could also suffer from this are `ComboBox` and `ColorPicker`, which both inherit from `PopupButton`.  So I think this solution should still fix both.  But since I'm not understanding how to reproduce the issue, I can't say for sure...

**Comment by crazycarl** [comment] 2018-04-04 20:53
I've never done a Pull Request before ~~noob status here~~ so I'll start by looking up a good tutorial on that.

I'll go hackup one of the examples to demo this crash first.

**Comment by crazycarl** [comment] 2018-04-04 21:10
I cobbled together this from example2.cpp. Just replace the contents of example2.cpp and you'll see the bug in action. Ohh, and follow the little instructions written on the buttons.

```c
/*
    src/example2.cpp -- C++ version of an example application that shows
    how to use the form helper class. For a Python implementation, see
    '../python/example2.py'.

    NanoGUI was developed by Wenzel Jakob <wenzel.jakob@epfl.ch>.
    The widget drawing code is based on the NanoVG demo application
    by Mikko Mononen.

    All rights reserved. Use of this source code is governed by a
    BSD-style license that can be found in the LICENSE.txt file.
*/

#include <nanogui/nanogui.h>
#include <iostream>

using namespace nanogui;

int main(int /* argc */, char ** /* argv */) {
    nanogui::init();

    /* scoped variables */ {
        bool use_gl_4_1 = false;// Set to true to create an OpenGL 4.1 context.
        Screen *screen = nullptr;

        if (use_gl_4_1) {
            // NanoGUI presents many options for you to utilize at your discretion.
            // See include/nanogui/screen.h for what all of these represent.
            screen = new Screen(Vector2i(500, 700), "NanoGUI test [GL 4.1]",
                                /*resizable*/true, /*fullscreen*/false, /*colorBits*/8,
                                /*alphaBits*/8, /*depthBits*/24, /*stencilBits*/8,
                                /*nSamples*/0, /*glMajor*/4, /*glMinor*/1);
        } else {
            screen = new Screen(Vector2i(500, 700), "NanoGUI test");
        }

        Window * window = screen->add<Window>("A window of nastiness");
        window->setLayout(new GroupLayout());

        PopupButton * popupButton = window->add<PopupButton>("Push this first");
        Popup * popup = popupButton->popup();
        popup->setLayout(new GroupLayout());
        popup->add<Label>("Now press that button which says \"Push this last\"");

        Button * close = window->add<Button>("Push this last");
        close->setCallback([window]()
        {
            window->dispose();
        });

        screen->setVisible(true);
        screen->performLayout();
        window->center();

        nanogui::mainloop();
    }

    nanogui::shutdown();
    return 0;
}
```

~~it feels good to be contributing to a project for once :)~~

**Comment by wjakob** [comment] 2018-04-10 21:42
Closing this, as #327 was merged. Thanks for the fix!

**Closed** 2019-05-19 05:24 UTC
