### ISSUE TITLE
Slider issue 

### ISSUE THREAD

**Issue by FredrickV** [wjakob/nanogui#161] opened 2016-10-28 23:49 UTC
Issue with the new scissor test that was just added (Worked before)
Slider handle cut in half
![image](https://cloud.githubusercontent.com/assets/11610494/19825456/b9ba594c-9d79-11e6-8181-58fc1132f904.png)

**Comment by fairlight1337** [comment] 2016-10-29 00:32
Hmm, looks like the Slider class is drawing outside its bounds. I didn't see this one; I'll check what size it reports and try to correct that later today.

Thanks for bringing this up - have you seen any other widgets with similar issues?

**Comment by FredrickV** [comment] 2016-10-29 00:36
Not yet, will test more in the morning. 

More widgets, looks good so far. (Last slider is also cut in half along the horizontal, that was not there either.

![image](https://cloud.githubusercontent.com/assets/11610494/19825912/51b7c012-9d80-11e6-9346-48eb1970a563.png)

**Comment by fairlight1337** [comment] 2016-10-29 04:06
Yep, there we have it: https://github.com/wjakob/nanogui/blob/master/src/slider.cpp#L56
```cpp
Vector2f knobPos(mPos.x() + (mValue - mRange.first) /
            (mRange.second - mRange.first) * mSize.x(), center.y() + 0.5f);
```
The knob center is at the slider's X position and potentislly goes to (X + Width). When drawn, it has a radius that gets drawn outside of the slider's `size()`. This wasn't an issue before the scissor change, you're right.

@wjakob I could imagine two ways out of this:

 1. Moving on the knob center a bit into the slider on both sides (by value of its radius). This would also make the slider slightly smaller horizontally.

 2. Defining a second property for widgets that defaults to `size()`, but can be specified to be a different scissor area for this widget (overridden in the class). This would allow the UI elements to overlap.

What would you say is a good way of handling this here?

**Comment by wjakob** [comment] 2016-10-30 10:21
Good catch. I think that the slider widget should restrain itself to only draw within its bounds. The solution will be to just make the horizontal range a tiny bit smaller and shift it towards the right by a few pixels.

**Comment by FredrickV** [comment] 2016-10-30 16:06
I don't want to have tiny knobs just for the sake of staying inside the slider boundary.. The boundary should be defined, including the knob not the other way around.

**Comment by wjakob** [comment] 2016-10-30 16:09
@FredrickV: Nobody is talking about making the knobs smaller

**Comment by FredrickV** [comment] 2016-10-30 16:35
Good, misunderstood

**Comment by fairlight1337** [comment] 2016-10-30 18:30
I just pushed a fix for the horizontal cut-off: 91d8bd688aebac77eb4d32a3cd0f1bf14d4f2927. I could reproduce the problem in `example1` and this commit solves that issue.

The vertical cut-off I couldn't reproduce, though. @FredrickV, how exactly did you configure the layout of the window and the slider itself? Does it have a fixed height?

Once that's solved as well I'll turn this into a proper PR.

**Comment by FredrickV** [comment] 2016-10-30 19:17
Knobs renders correctly again, awesome 

![image](https://cloud.githubusercontent.com/assets/11610494/19839196/dd0a181e-9edd-11e6-937e-eae4420b54fc.png)


This is the code, if horizontal it gets cut in half, may be a fault in my code. I could set minimum size on the slider widget to solve it
```
widget_slider_frame GUIWidgets::CreateSliderFrame(nanogui::Widget *parentWindow,
												  const std::string &title,
												  const float valueMin,
												  const float valueMax,
												  const float value,
												  const bool horizontal)
{
	widget_slider_frame frame;

	frame.labelTitle = new nanogui::Label(parentWindow, title, "sans-bold", 25/*, NVG_ALIGN_MIDDLE*/);
	frame.widgetContainer = new nanogui::Widget(parentWindow);

	GridLayout *layout = nullptr;
	if (horizontal) {
		layout = new GridLayout(Orientation::Horizontal, 2,
			Alignment::Minimum, 0, 10);
		frame.widgetContainer->setLayout(layout);
	}
	else {
		layout = new GridLayout(Orientation::Vertical, 2,
			Alignment::Minimum, 0, 10);
		frame.widgetContainer->setLayout(layout);
	}

	char buffer[56];
	sprintf(buffer, "%.1f", value);
	frame.sliderValueLabel = new nanogui::Label(frame.widgetContainer, buffer, "sans", 20/*, NVG_ALIGN_LEFT*/);

	sprintf(buffer, "Valid Range: %.2f - %.2f", valueMin, valueMax);
	frame.labelTitle->setTooltip(buffer);

	frame.slider = new nanogui::Slider(frame.widgetContainer);
	frame.slider->setValue(value / valueMax);
	frame.slider->setFixedWidth(parentWindow->fixedWidth() - 130);

	return frame;
}
```

**Comment by fairlight1337** [comment] 2016-10-30 20:17
Thanks for the code.

It might be the `GridLayout` as that's the only thing you're using that I'm not totally familiar with (the rest looks very innocent). I'll do some tests and see if I can reproduce and potentially get rid of the problem.

**Comment by wjakob** [comment] 2016-10-30 21:05
@fairlight1337: can you submit your patch as a PR? Thanks!

**Comment by fairlight1337** [comment] 2016-10-30 21:08
@wjakob Alright, will do; I planned to wait until figuring out the vertical cut-off as well, but that can be a separate thing (as the current one is far more often apparently).

**Comment by FredrickV** [comment] 2016-10-30 21:11
I will do some more investigation as well.

Thanks for the support and good work!

**Closed** 2016-10-31 11:45 UTC
